name: test workflow call

on: 
  workflow_dispatch:
    inputs: 
      name: 
        type: string
        required: true
      file-path:
        type: string
        required: true

jobs:
  publish-techdocs:
    name: Publish docs
    uses: nick-gray-bah/image-host/.github/workflows/test-encrypted-artifact.yaml@main
    with:
      name: ${{ inputs.name }}
      path: ${{ inputs.file-path }}
    secrets: inherit