
on: 
  workflow_dispatch:

jobs:
  publish-techdocs:
    name: Publish docs
    uses: nick-gray-bah/image-host/.github/workflows/test-encrypted-artifact.yaml@main
    with:
      name: test-file
      file: test-file.txt
    secrets: inherit